CREATE DATABASE swiftiedb;
USE swiftiedb;

SHOW TABLES;

DROP TABLE IF EXISTS USERPAYMENT_TB;
DROP TABLE IF EXISTS ORDERITEM_TB;
DROP TABLE IF EXISTS TRANSACTION_TB;
DROP TABLE IF EXISTS PURCHASEORDERITEM_TB;
DROP TABLE IF EXISTS PURCHASEORDER_TB;
DROP TABLE IF EXISTS INVENTORY_TB;
DROP TABLE IF EXISTS SUPPLIER_TB;
DROP TABLE IF EXISTS MENUITEM_TB;
DROP TABLE IF EXISTS USER_TB;

SHOW TABLES;

CREATE TABLE IF NOT EXISTS USER_TB (
    UserID INT AUTO_INCREMENT NOT NULL,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Email VARCHAR(250) NOT NULL,
    PhoneNum VARCHAR(15) NOT NULL,
    UserType VARCHAR(2) NOT NULL,
    Active BOOLEAN NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS USERPAYMENT_TB (
    UserPaymentID INT AUTO_INCREMENT NOT NULL,
    PaymentType VARCHAR(50) NOT NULL,
    NameOnCard VARCHAR(50) NOT NULL,
    CardNum VARCHAR(50) NOT NULL,
    CardExpiry VARCHAR(20) NOT NULL,
    CardCVV VARCHAR(20) NOT NULL,
    DefaultPayment BOOLEAN NOT NULL,
    UserID INT NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserPaymentID),
    FOREIGN KEY (UserID)
        REFERENCES USER_TB (UserID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MENUITEM_TB (
    MenuItemID INT AUTO_INCREMENT NOT NULL,
    ItemDescription VARCHAR(500),
    ItemPrice DOUBLE,
    ItemStatus BOOLEAN,
    ItemCategory VARCHAR(20),
	Seasonal BOOLEAN,
    ImageFilePath VARCHAR(500),
    ThresholdQuantity INT,
    AvailableQuantity INT,
    ItemName VARCHAR(100),
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MenuItemID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS SUPPLIER_TB (
    SupplierID INT AUTO_INCREMENT NOT NULL,
    SupplierName VARCHAR(100) NOT NULL,
    SupplierAddress VARCHAR(500) NOT NULL,
    SupplierPhoneNum VARCHAR(20) NOT NULL,
    SupplierOfficeNum VARCHAR(20) NOT NULL,
    SupplierWebsite VARCHAR(70),
    SupplierEmail VARCHAR(250) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SupplierID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS INVENTORY_TB (
    InventoryID INT AUTO_INCREMENT,
    InventoryDescription VARCHAR(500),
    InventoryPrice DOUBLE NOT NULL,
    Quantity INT,
    SupplierID INT,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (InventoryID),
    FOREIGN KEY (SupplierID)
        REFERENCES SUPPLIER_TB (SupplierID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TRANSACTION_TB (
    TransactionID INT AUTO_INCREMENT NOT NULL,
    PaymentType VARCHAR(20) NOT NULL,
    GrandTotal DOUBLE NOT NULL,
    TransactionDate DATETIME NOT NULL,
    TransactionStatus VARCHAR(1) NOT NULL,
    OrderStatus VARCHAR(20) NOT NULL,
    UserID INT NOT NULL,
    PosID INT,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TransactionID),
    FOREIGN KEY (UserID)
        REFERENCES USER_TB (UserID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY (PosID)
        REFERENCES USER_TB (UserID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ORDERITEM_TB (
    OrderItemID INT AUTO_INCREMENT NOT NULL,
    Quantity INT NOT NULL,
    SubTotal DOUBLE NOT NULL,
    SpecialRequest VARCHAR(500),
    UserID INT NOT NULL,
    MenuItemID INT NOT NULL,
    TransactionID INT NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (OrderItemID),
    FOREIGN KEY (UserID)
        REFERENCES USER_TB (UserID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (MenuItemID)
        REFERENCES MENUITEM_TB (MenuItemID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (TransactionID)
        REFERENCES TRANSACTION_TB (TransactionID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PURCHASEORDER_TB (
    PurchaseOrderID INT AUTO_INCREMENT NOT NULL,
    RequestDate DATETIME NOT NULL,
    Status VARCHAR(10) NOT NULL,
    GrandTotal DOUBLE NOT NULL,
    SmID INT NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PurchaseOrderID),
    FOREIGN KEY (SmID)
        REFERENCES USER_TB (UserID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PURCHASEORDERITEM_TB (
    PurchaseOrderItemID INT AUTO_INCREMENT NOT NULL,
    Quantity INT NOT NULL,
    SubTotal DOUBLE NOT NULL,
    InventoryID INT NOT NULL,
    SupplierID INT NOT NULL,
    PurchaseOrderID INT NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PurchaseOrderItemID),
    FOREIGN KEY (InventoryID)
        REFERENCES Inventory_TB (InventoryID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (SupplierID)
        REFERENCES SUPPLIER_TB (SupplierID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (PurchaseOrderID)
        REFERENCES PURCHASEORDER_TB (PurchaseOrderID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MENUITEM_INVENTORY_TB (
    MenuItemInventoryID INT AUTO_INCREMENT NOT NULL,
    MenuItemID INT NOT NULL,
    InventoryID  INT NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MenuItemInventoryID),
    FOREIGN KEY (MenuItemID)
        REFERENCES MENUITEM_TB (MenuItemID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (InventoryID)
        REFERENCES INVENTORY_TB (InventoryID)
        ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=INNODB;

SHOW TABLES;