DELETE FROM USER_TB;
DELETE FROM USERPAYMENT_TB;
DELETE FROM SUPPLIER_TB;
DELETE FROM MENUITEM_TB;
DELETE FROM INVENTORY_TB;
DELETE FROM MENUITEM_INVENTORY_TB;

-- USER TABLE
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Craig','Mcdonald','Nunc@tellusNunclectus.ca','90075389','SA',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Vance','Solomon','aliquet.Proin.velit@ut.org','90051985','SM',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Brett','Horne','Class.aptent.taciti@Proin.com','90042958','SM',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Jesse','Stephens','felis@ipsum.edu','90004338','SM',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Elvis','Nunez','Duis.volutpat@aliquetnecimperdiet.ca','90068787','PO',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Erasmus','Nielsen','nec.eleifend.non@vitae.ca','90074838','PO',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Emmanuel','Hall','Proin.non@elit.net','90016573','PO',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Kennedy','Aguilar','sociis@Nulladignissim.org','90055393','KS',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Gregory','Lawson','ut@Nunc.co.uk','90051968','KS',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Brody','Hicks','enim.Nunc.ut@eleifend.org','90012277','KS',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Linus','Montoya','eu.accumsan@Nullamutnisi.edu','90053402','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Elmo','Mays','non@semsemper.com','90073562','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Colorado','Moon','dapibus@pharetrautpharetra.ca','90099922','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Thor','Valdez','Nullam@Quisquenonummy.co.uk','90029585','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Erasmus','Bartlett','augue.eu@ultriciessemmagna.net','90057390','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Bruno','Rivas','nonummy@eusemPellentesque.edu','90032753','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Joshua','Morton','dis@luctusut.ca','90039232','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Thaddeus','Villarreal','in.cursus.et@odioEtiamligula.co.uk','90025451','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Fitzgerald','White','Duis.cursus@sitamet.edu','90028836','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Harper','Hammond','malesuada@Aliquamgravida.net','90046997','CU',TRUE);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('System','Admin','sa@email.com','91234567','SA',1);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Store','Manager','sm@email.com','91234567','SM',1);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Point Of Sale','POS','pos@email.com', '91234567', 'PO',1);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Kitchen','Staff','ks@email.com', '91234567', 'KS',1);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Dennis','Tandian','dennistandian@gmail.com','91234567','CU',1);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active)VALUES ('Michelle','Wong','mishieeru20@gmail.com','91234567','CU',1);
INSERT INTO USER_TB (FirstName,LastName,Email,PhoneNum,UserType,Active) VALUES ('Michellie', 'Wong', 'mwtwong001@mymail.sim.edu.sg', '88880000', 'CU', '1');


-- USER PAYMENT TABLE
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Jarrod Glover','5203461792559650','01/20','744','1','1');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Wylie Ratliff','5346730789877470','02/20','289','1','2');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Miriam King','5468674464632980','09/19','742','1','3');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Dana Hubbard','5520914721387180','03/20','829','1','4');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Burton Padilla','5241547547351760','10/19','724','1','5');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Adrian Wolf','5242388609923880','12/19','729','1','6');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Sebastian Mack','5264939586230290','06/19','394','1','7');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Alexander Frank','5184331008231710','12/19','828','1','8');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Fletcher Weeks','5123183521647920','01/19','118','1','9');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Isadora Flynn','5594801590869240','07/19','349','1','10');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Roth Mckinney','5225713885754550','01/20','285','1','11');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Calista Wall','5375874573276030','08/20','205','1','12');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Madaline Gordon','5171875301363540','04/19','649','1','13');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Kane Parrish','5567772071572120','05/19','783','1','14');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Kelly Webster','5157558574585400','07/20','622','1','15');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Oleg Matthews','5114658862575990','04/20','578','1','16');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Quinn Stein','5145332178917960','10/20','446','1','17');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Ciaran Alford','5477551626403900','10/19','851','1','18');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Idola Smith','5543135103946590','09/19','911','1','19');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Mastercard','Demetria Walter','5414497161584050','04/19','404','1','20');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Glenna Cooke','5214484285733250','02/19','538','1','1');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Marcia Eaton','5482440226576970','09/19','436','1','2');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Rylee Ewing','5420818426268180','05/19','468','1','3');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Teagan Sargent','5273538590627430','11/19','645','1','4');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Rigel Case','5346542169335570','12/20','292','1','5');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Erin Burris','5247300125645810','10/19','451','1','6');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Jena Middleton','5413828779712280','12/20','523','1','7');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Derek Wong','5598331766304970','10/19','289','0','8');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Lucas Saunders','5276046894359610','12/19','350','0','9');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Wyoming Mcgee','5149638585339980','06/19','787','0','10');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Cheyenne Dejesus','5366631525191720','06/19','538','0','11');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Logan Newton','5201805838716510','07/20','375','0','12');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Mikayla Fleming','5585313526878930','10/19','469','0','13');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Adria Farmer','5128952849008050','02/20','309','0','14');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Bevis Warren','5211361261834180','04/20','874','0','15');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','April Wolfe','5505030195929610','11/20','130','0','16');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Arthur Burton','5586555486823330','03/20','857','0','17');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Isadora Logan','5207074412328920','03/20','758','0','18');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Daquan Reese','5508278824175290','04/19','449','0','19');
INSERT INTO USERPAYMENT_TB (PaymentType,NameOnCard,CardNum,CardExpiry,CardCVV,DefaultPayment,UserID)VALUES ('Visa','Yvette Molina','5338393645231750','03/19','402','0','20');

-- INVENTORY TABLE
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Chicken Cutlet','3','50','1');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Fries (Shoestrings)','3','50','2');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Sausage (Brawurst)','3.5','50','4');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Sirloin Beef','5','50','5');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Chicken Wing','2','50','6');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Beef Steak (Raw)','4','50','7');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Prawn','2','50','8');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Pasta','1.5','50','9');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Chicken Chunks','2.5','50','10');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Chicken Breast','2.5','50','11');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Rice','1','50','12');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Beef Chunks','3','50','13');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Rendang Sauce','2','50','14');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Beef Patty','3','50','15');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Burger Bun','1','50','16');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Cheddar Cheese','1','50','17');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Pizza Dough','1','50','18');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Pepperoni','3','50','19');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Mozzarella Cheese','2','50','20');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Mixed Veggie','1','50','21');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Chicken Ham','2','50','22');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Egg','1','50','23');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Tuna','2','50','24');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Croissant','2','50','25');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Toast','2','50','26');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Almond','2','50','27');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Flour','1','50','28');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Chocolate','1','50','29');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Cappucino Powder','1','50','30');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Tea','1','50','31');
INSERT INTO INVENTORY_TB (InventoryDescription,InventoryPrice,Quantity,SupplierID)VALUES ('Blueberries','1','50','32');

-- MENUITEM TABLE
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Chicken Chop','10','TRUE','Western','FALSE','https://cdn.pixabay.com/photo/2015/09/09/19/42/french-fries-932849_960_720.jpg','50','6');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Sausage','9','TRUE','Sides','FALSE','https://cdn.pixabay.com/photo/2017/07/30/18/41/bratwurst-2555218_960_720.jpg','50','9');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Sirloin Steak','15','TRUE','Western','TRUE','https://cdn.pixabay.com/photo/2018/09/14/11/12/food-3676796_960_720.jpg','50','10');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Chicken Wings','7','TRUE','Sides','FALSE','https://cdn.pixabay.com/photo/2017/09/03/01/17/wings-2709068_960_720.jpg','50','5');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Beef Steak','15','TRUE','Western','FALSE','https://cdn.pixabay.com/photo/2015/02/04/08/45/beef-623465_960_720.jpg','50','7');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Prawn Pasta','10','TRUE','Western','FALSE','https://cdn.pixabay.com/photo/2014/09/11/11/17/prawn-441623_960_720.jpg','50','5');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Chicken Pasta','10','TRUE','Western','FALSE','https://cdn.pixabay.com/photo/2014/01/03/03/02/spaghetti-237907_960_720.jpg','50','6');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Chicken Rice','8','TRUE','Asian','FALSE','https://cdn.pixabay.com/photo/2018/07/31/10/38/food-3574728_960_720.jpg','50','5');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Beef Rendang','9','TRUE','Asian','TRUE','https://cdn.pixabay.com/photo/2015/01/23/10/57/asian-food-608973_960_720.jpg','50','8');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Cheese Burger','9','TRUE','Western','FALSE','https://cdn.pixabay.com/photo/2017/07/31/17/16/burger-2559087_960_720.jpg','50','10');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Signature Pizza','15','TRUE','Western','TRUE','https://cdn.pixabay.com/photo/2017/12/09/08/18/pizza-3007395_960_720.jpg','50','10');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Bibimbap','8','TRUE','Asian','TRUE','https://cdn.pixabay.com/photo/2017/08/08/09/44/food-photography-2610863_960_720.jpg','50','5');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('All Day Breakfast','9','TRUE','Western','TRUE','https://cdn.pixabay.com/photo/2015/01/23/07/13/all-day-608802_960_720.jpg','50','8');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Tuna Croissant','4.5','TRUE','Sides','FALSE','https://cdn.pixabay.com/photo/2017/04/12/03/49/croissant-2223561_960_720.jpg','50','8');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Breakfast Toast','4.5','TRUE','Sides','FALSE','https://cdn.pixabay.com/photo/2020/01/10/09/30/breakfast-4754868_960_720.jpg','50','9');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Almond Cake','7','TRUE','Desserts','TRUE','https://cdn.pixabay.com/photo/2015/02/04/08/06/dessert-623420_960_720.jpg','50','6');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Chocolate Cake','6.5','TRUE','Desserts','FALSE','https://cdn.pixabay.com/photo/2015/02/04/10/15/cake-623579_960_720.jpg','50','9');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Pancake','6','TRUE','Desserts','FALSE','https://cdn.pixabay.com/photo/2019/12/28/15/14/pancake-4724890_960_720.jpg','50','10');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Cappuccino','3.5','TRUE','Drinks','FALSE','https://cdn.pixabay.com/photo/2015/02/04/06/42/cup-623386_960_720.jpg','50','10');
INSERT INTO MENUITEM_TB (ItemDescription,ItemPrice,ItemStatus,ItemCategory,Seasonal,ImageFilePath,ThreshHoldQuantity,AvailableQuantity)VALUES ('Black Tea','3','TRUE','Drinks','FALSE','https://cdn.pixabay.com/photo/2017/12/27/19/19/coffee-3043424__340.jpg','50','8');

-- SUPPLIER TABLE
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Donec Est Ltd','Ap #902-3048 Dapibus St.','94055291','64082348','Darrel.com','ligula.elit@quisturpis.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Malesuada Id Erat Limited','7411 Facilisis St.','94075806','64006170','Benedict.com','ut@nislNulla.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Sit Amet Associates','Ap #631-8730 Lobortis St.','94023362','64097363','Stephen.com','hendrerit@elitfermentum.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('In Consulting','Ap #600-1921 Orci, St.','94068037','64063267','Rebekah.com','non@elitpede.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Nascetur Ridiculus LLP','136-1577 Et Avenue','94074803','64069471','Iliana.com','In.condimentum.Donec@rhoncus.net');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Phasellus Incorporated','P.O. Box 810, 695 Aenean Av.','94009758','64006646','Amela.com','arcu.Aliquam@liberoProin.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Egestas Urna Institute','923-5856 Orci Road','94061768','64008186','Alyssa.com','nec@semut.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Dignissim Lacus Aliquam LLP','4830 Tempus Avenue','94026864','64047088','Vivian.com','Mauris.vestibulum.neque@nuncQuisqueornare.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Neque Vitae Semper Company','P.O. Box 814, 8264 Accumsan Rd.','94072963','64082528','Stacy.com','dolor@dignissimMaecenas.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Velit Foundation','P.O. Box 103, 4274 Sem, Road','94005279','64034843','Charissa.com','massa.Integer.vitae@leo.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Lacus Limited','Ap #957-594 Integer Road','94076962','64030553','Quon.com','semper.erat@nuncinterdum.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Vitae Sodales Nisi Foundation','717-9916 Eleifend Road','94085108','64058543','Sydnee.com','Mauris.nulla@nunc.co.uk');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Fringilla Donec Feugiat LLC','6175 Litora Road','94061980','64038149','Teegan.com','nec.mauris.blandit@massa.net');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Conubia Nostra Incorporated','3861 Pharetra. Road','94065834','64045386','Joseph.com','Nulla@pellentesque.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Quam Quis Diam LLC','P.O. Box 209, 4349 Convallis St.','94025479','64090466','Barrett.com','amet.nulla@augue.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Ipsum Company','P.O. Box 177, 1897 Imperdiet Road','94049414','64012186','Justin.com','fermentum.arcu@necdiam.co.uk');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Eleifend LLC','741-7404 Lorem Av.','94079598','64046572','Damian.com','Nulla.tempor@molestie.co.uk');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Quis Company','P.O. Box 501, 1321 Ante, Av.','94093742','64093093','Ora.com','ante.dictum@neque.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Purus LLP','P.O. Box 489, 2839 Cubilia St.','94002351','64090280','Velma.com','ut.odio@ipsumdolorsit.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Nec Ligula Corporation','P.O. Box 204, 3410 Ornare, Street','94012903','64073751','Dante.com','varius.et.euismod@imperdiet.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Ornare Tortor At Industries','5560 Nulla Av.','94022586','64089192','Carol.com','consectetuer.adipiscing.elit@malesuadafames.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Magna Phasellus Dolor Consulting','6091 Magna Street','94049665','64031737','Ria.com','augue.scelerisque.mollis@SuspendisseduiFusce.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Tincidunt LLC','493-5344 Massa. Rd.','94094051','64080754','Ila.com','mi.lorem@antelectus.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Odio Consulting','Ap #693-7827 Volutpat St.','94089580','64008863','Mason.com','a.magna@in.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Lacus Limited','670-2294 Suspendisse Rd.','94004227','64027458','Isaac.com','Vestibulum.accumsan.neque@tellusimperdietnon.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Pellentesque Ultricies Dignissim Consulting','P.O. Box 505, 4984 Sed Street','94018142','64076463','Grant.com','Phasellus.fermentum.convallis@dictumsapienAenean.net');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('In Lorem Donec Company','Ap #906-2300 Dui Rd.','94088646','64080508','Hamilton.com','sit@porttitorscelerisque.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Nunc Commodo Auctor LLC','Ap #578-1280 Et, Rd.','94090680','64017678','Lois.com','Phasellus.nulla@Nam.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Leo Vivamus Industries','8176 Blandit Road','94083946','64013366','Erica.com','venenatis@odioapurus.co.uk');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Justo LLP','230 Lorem Rd.','94076235','64071121','Lucian.com','Pellentesque.ut@Pellentesquehabitant.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Imperdiet Incorporated','P.O. Box 280, 3400 Libero Avenue','94074388','64053898','Sheila.com','Etiam@feugiatnecdiam.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Nam Porttitor Corp.','Ap #150-5086 At Rd.','94048341','64094008','Chantale.com','et.lacinia@Quisqueac.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Parturient Montes Limited','Ap #739-7893 Aliquam Rd.','94017631','64058488','Bethany.com','ut.pellentesque@cursusaenim.co.uk');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Tempor Est Ac Ltd','P.O. Box 382, 5910 Urna. Avenue','94096931','64042443','Jade.com','Suspendisse@Vivamusmolestie.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Ut Molestie LLC','P.O. Box 274, 7042 Id, St.','94058195','64037057','Rafael.com','Proin.velit.Sed@nequeInornare.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Sit Amet Ultricies Associates','P.O. Box 909, 9826 Diam. Av.','94048295','64082544','Desiree.com','tincidunt@orci.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Pede Nec Ante Corp.','Ap #915-2107 Porttitor St.','94088577','64086708','Anjolie.com','tellus@uteros.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Vulputate Ullamcorper LLC','2161 Lobortis St.','94078199','64087252','Lael.com','Integer.in.magna@purusaccumsaninterdum.edu');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Elementum PC','6055 Mattis Ave','94004049','64009633','Demetrius.com','feugiat.nec.diam@amet.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Mauris Vestibulum Inc.','9229 Ligula. Road','94086907','64065804','Kuame.com','placerat@venenatisvelfaucibus.co.uk');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Magna Sed Corporation','1683 Sed Avenue','94039837','64023584','Mercedes.com','eget.massa@egestasrhoncusProin.co.uk');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Est Vitae Sodales Associates','629-2179 Nec, Rd.','94012993','64089484','Pandora.com','lorem@Cras.net');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Nulla At Institute','P.O. Box 142, 5221 Aenean Rd.','94053268','64004924','Britanney.com','accumsan.interdum@malesuada.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('A Felis Ullamcorper Industries','P.O. Box 629, 3696 Maecenas St.','94006288','64051534','Russell.com','euismod.ac@Morbisit.net');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Lacus Etiam Bibendum Ltd','Ap #534-9339 Libero Road','94080233','64028669','Kelly.com','ultrices.Duis.volutpat@commodoat.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Cras Eu Tellus Inc.','4342 Urna. Street','94030915','64025224','Erica.com','netus@elit.ca');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Duis Dignissim Associates','P.O. Box 421, 2761 Nibh Av.','94073344','64034107','Xander.com','tempor.augue.ac@Maurisquis.com');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Nunc Ac Institute','Ap #890-1088 Scelerisque, Av.','94083014','64016967','Lyle.com','ipsum@sitamet.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Aliquet Company','6831 Tincidunt Ave','94022304','64066226','Mariko.com','in.consectetuer.ipsum@ettristiquepellentesque.org');
INSERT INTO SUPPLIER_TB (SupplierName,SupplierAddress,SupplierPhoneNum,SupplierOfficeNum,SupplierWebsite,SupplierEmail)VALUES ('Fringilla Cursus Purus PC','277-4181 Etiam Rd.','94077075','64011966','Adele.com','aliquam@libero.com');

-- MENU ITEM INVENTORY TABLE
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('1','2');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('2','3');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('3','2');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('3','4');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('4','5');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('5','6');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('5','2');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('5','20');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('6','7');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('6','8');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('7','8');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('7','9');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('8','10');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('8','11');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('9','12');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('9','13');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('9','22');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('10','14');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('10','15');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('10','16');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('10','2');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('11','17');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('11','18');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('11','19');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('12','20');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('12','21');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('12','22');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('12','11');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('13','22');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('13','15');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('13','21');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('13','3');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('14','23');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('14','24');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('14','20');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('15','22');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('15','25');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('15','2');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('16','26');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('16','27');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('17','27');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('17','28');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('17','29');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('18','22');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('18','27');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('18','31');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('19','32');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('19','33');
INSERT INTO MENUITEM_INVENTORY_TB (MenuItemID,InventoryID)VALUES ('20','30');